/* Step 1: Print SASHELP.CARS */
proc print data=sashelp.cars (obs=10);
run;

/* Step 2: Sort data by type and MSRP */
proc sort data=sashelp.cars out=cars_sorted;
  by type MSRP;
run;
/* Step 3: Create mpg_avg */
data cars_new;
  set cars_sorted;
  mpg_avg = (mpg_city + mpg_highway) / 2;
run;

proc print data=cars_new (obs=10);
run;

/* Step 4: Create Scatter Plot */

	SYMBOL1
	INTERPOL=NONE
	HEIGHT=10pt
	VALUE=CIRCLE
	LINE=1
	WIDTH=2

	CV = _STYLE_
;
Axis1
	STYLE=1
	WIDTH=1
	MINOR=NONE
;
Axis2
	STYLE=1
	WIDTH=1
	MINOR=NONE
;
TITLE;
TITLE1 "Scatter Plot";
FOOTNOTE;
FOOTNOTE1 "Generated by the SAS System (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%SYSFUNC(TIME(), TIMEAMPM12.))";

PROC GPLOT DATA=cars_new;
PLOT MPG_Highway * MPG_City / 
	VAXIS=AXIS1

	HAXIS=AXIS2

FRAME ;
/* -------------------------------------------------------------------
   End of task code
   ------------------------------------------------------------------- */
RUN; QUIT;
%_eg_conditional_dropds(WORK.SORTTempTableSorted);
TITLE; FOOTNOTE;
GOPTIONS RESET = SYMBOL;

/* Step 5: Create cars table where origin is just USA */ 
data cars_usa;
  set cars_new;
  if origin = "USA" and type = "SUV"; /* Step #7 - add type to filter */
run;

/*Step 6: sort cars usa by make and model*/
proc sort data=cars_usa out=cars_usa_sorted;
  by make model;
run;

/* Step 8 - reduce obs to list to 10 */
proc print data=cars_usa_sorted (obs=10);
  var make model mpg_highway mpg_city; /* Step #8: limit vars in list rpt */
run;  

/* Step #9 - Pie Chart of USA Makes */
TITLE;
TITLE1 "Pie Chart";
TITLE2 "Frequency of Makes for US Cars";  /* Step #10 - Change Title */
FOOTNOTE;
FOOTNOTE1 "Generated by the SAS System (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%SYSFUNC(TIME(), TIMEAMPM12.))";
PROC GCHART DATA =cars_usa_sorted
;
	PIE	 Make /
 	NOLEGEND
	SLICE=OUTSIDE
	PERCENT=NONE
	VALUE=OUTSIDE
	OTHER=4
	OTHERLABEL="Other"
	COUTLINE=BLACK
NOHEADING
;
/* -------------------------------------------------------------------
   End of task code
   ------------------------------------------------------------------- */
RUN; QUIT;

/* GET RID OF PROC PRINT */